plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dhruv.dhruvtube'
    compileSdk 33

    defaultConfig {
        applicationId 'com.dhruv.dhruvtube'
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }

    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets']
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
}
